DELETE FROM SOURCE_VALUE;
DELETE FROM SOURCE_LOCATION;
DELETE FROM SOURCE_ATTRIBUTE;
--DELETE FROM sqlite_sequence; -- WHERE name='your_table';
DROP TABLE IF EXISTS SOURCE_VALUE;
DROP TABLE IF EXISTS SOURCE_LOCATION;
DROP TABLE IF EXISTS SOURCE_ATTRIBUTE;