server:
  port: 8081
input:
  dir: "/Users/sooraj.a.nair/Library/CloudStorage/OneDrive-Accenture/Engagements/Sales/Global_Demand"
  file: "/Users/sooraj.a.nair/Library/CloudStorage/OneDrive-Accenture/Engagements/Sales/Global_Demand/Global_demand_Oct_31.xlsx"
  columnsDef: "/Users/sooraj.a.nair/Library/CloudStorage/OneDrive-Accenture/Engagements/Sales/Global_Demand/columnsDef.yml"
  rowsDef: "/Users/sooraj.a.nair/Library/CloudStorage/OneDrive-Accenture/Engagements/Sales/Global_Demand/rowsDef.yml"
javax:
  persistence:
    schema-generation:
      scripts:

spring:
  application:
    name: excel-filter-copier-standalone
  batch:
    initialize-schema: always
    job:
      enabled: true
    #table-prefix: batchmetadata.BATCH_
  datasource:
    url: "jdbc:sqlite:database/export.db"
    driver-class-name: "org.sqlite.JDBC"
    username: ""
    password: ""
    #initialization-mode: always
  jpa:
    database-platform: "com.conserwit.excel.filter.copier.standalone.data.repository.SQLiteDialect"
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    fail-on-missing-locations: true
    locations: filesystem:database/scripts/migrate #classpath:db/migrate
    user: ""
    password: ""
    schemas: ""
    #init-sqls: "SELECT * FROM SPREADSHEET_COLUMN ORDER BY SS_CID"
# spring.main.banner-mode=off
spreadsheet:
  column:
    query:
      find:
        all: "SELECT * FROM SPREADSHEET_COLUMN ORDER BY SS_CID"
      delete:
        all: "DELETE FROM SPREADSHEET_COLUMN"
  cell:
    query:
      find:
        all: "SELECT * FROM SPREADSHEET_CELL ORDER BY SS_CID, SS_ID"
      delete:
        all: "DELETE FROM SPREADSHEET_CELL"
logging:
  level:
    root=debug: