CREATE TABLE IF NOT EXISTS SOURCE_ATTRIBUTE (SA_ID INTEGER PRIMARY KEY AUTOINCREMENT, SA_NAME VARCHAR NOT NULL UNIQUE, SA_TYPE VARCHAR NOT NULL);
CREATE TABLE IF NOT EXISTS SOURCE_LOCATION (SL_ID INTEGER PRIMARY KEY AUTOINCREMENT, ROW_INDEX INTEGER NOT NULL, SHEET_INDEX INTEGER NOT NULL, ORIGIN VARCHAR NOT NULL);
CREATE TABLE IF NOT EXISTS SOURCE_VALUE (SV_ID INTEGER PRIMARY KEY AUTOINCREMENT, SL_ID INTEGER NOT NULL, SA_ID INTEGER NOT NULL, SV_VALUE VARCHAR, FOREIGN KEY (SA_ID) REFERENCES SOURCE_ATTRIBUTE (SA_ID), FOREIGN KEY (SL_ID) REFERENCES SOURCE_LOCATION (SL_ID));
